version: "3.8"

services:
  mysqldb:
    image: mysql
    restart: no
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQLDB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQLDB_DATABASE}
    ports:
      - "${MYSQLDB_LOCAL_PORT}:${MYSQLDB_DOCKER_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -P ${MYSQLDB_DOCKER_PORT} -u ${MYSQLDB_USER} -p${MYSQLDB_ROOT_PASSWORD}"]
      interval: 30s
      timeout: 10s
      retries: 3

  app:
    depends_on:
     mysqldb:
       condition: service_healthy
    restart: on-failure
    image: book-store
    build: .
    ports:
      - "${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}"
      - "${DEBUG_PORT}:${DEBUG_PORT}"
    environment:
      SPRING_APPLICATION_JSON: '{
      "spring.datasource.url": "jdbc:mysql://mysqldb:${MYSQLDB_DOCKER_PORT}/${MYSQLDB_DATABASE}",
      "spring.datasource.username": "${MYSQLDB_USER}",
      "spring.datasource.password": "${MYSQLDB_ROOT_PASSWORD}",
      "jwt.expiration": "${JWT_EXPIRATION}",
      "jwt.secret": "${JWT_SECRET}"
      }'
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"